language: ruby

RVM:
  - 1.9
  - 2.0
  - 2.1
  - 2.2

git:
  submodules: false
  
sudo: false

before_install:
  - gem update --system
  - gem --version

script:
  - ruby --verbose download-atlas-upload.rb

after_script:
  - ls -al
  - pwd

env:
  - LANG="en_US.UTF-8"

os:
  - linux
