language: ruby

RVM:
  - 1.9
  - 2.0
  - 2.1
  - 2.2

git:
  submodules: false
  
sudo: false

script:
  - ruby --verbose download-atlas-upload.rb

after_script:
  - ls -al

env:
  - LANG="en_US.UTF-8"

os:
  - linux
