language: ruby

RVM:
  - 1.9.3
  - 2.2.3

git:
  submodules: false
  
sudo: false

install:
  - gem update --system
  - gem install rubyzip
  - gem --version

script:
  - ruby --verbose download-atlas-upload.rb
  - [ -f atlas-upload ]

after_script:
  - ls -al
  - pwd

env:
  - LANG="en_US.UTF-8"

os:
  - linux
